; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: llvm-as %s -o - | llvm-dis - | FileCheck %s

define void @test_all_revs(<vscale x 16 x i1> %a_i1, <vscale x 4 x i32> %a_i32, <vscale x 2 x i64> %a_i64, <vscale x 8 x half> %a_f16, ptr %out_i32) {
; CHECK-LABEL: define void @test_all_revs(
; CHECK-SAME: <vscale x 16 x i1> [[A_I1:%.*]], <vscale x 4 x i32> [[A_I32:%.*]], <vscale x 2 x i64> [[A_I64:%.*]], <vscale x 8 x half> [[A_F16:%.*]], ptr [[OUT_I32:%.*]]) {
; CHECK-NEXT:    [[RES_I1:%.*]] = call <vscale x 16 x i1> @llvm.vector.reverse.nxv16i1(<vscale x 16 x i1> [[A_I1]])
; CHECK-NEXT:    [[RES_I2:%.*]] = call <vscale x 16 x i1> @llvm.vector.reverse.nxv16i1(<vscale x 16 x i1> [[A_I1]])
; CHECK-NEXT:    [[RES_I32:%.*]] = call <vscale x 4 x i32> @llvm.vector.reverse.nxv4i32(<vscale x 4 x i32> [[A_I32]])
; CHECK-NEXT:    [[RES_I64:%.*]] = call <vscale x 2 x i64> @llvm.vector.reverse.nxv2i64(<vscale x 2 x i64> [[A_I64]])
; CHECK-NEXT:    [[RES_F16:%.*]] = call <vscale x 8 x half> @llvm.vector.reverse.nxv8f16(<vscale x 8 x half> [[A_F16]])
; CHECK-NEXT:    ret void
;
  %res = call <vscale x 16 x i1> @llvm.aarch64.sve.rev(<vscale x 16 x i1> %a_i1)
  %res_i1 = call <vscale x 16 x i1> @llvm.aarch64.sve.rev.nxv16i1(<vscale x 16 x i1> %a_i1)
  %res_i32 = call <vscale x 4 x i32> @llvm.aarch64.sve.rev.nxv4i32(<vscale x 4 x i32> %a_i32)
  %res_i64 = call <vscale x 2 x i64> @llvm.aarch64.sve.rev.nxv2i64(<vscale x 2 x i64> %a_i64)
  %res_f16 = call <vscale x 8 x half> @llvm.aarch64.sve.rev.nxv8f16(<vscale x 8 x half> %a_f16)  ret void
}


declare <vscale x 16 x i1> @llvm.aarch64.sve.rev(<vscale x 16 x i1>) #0
declare <vscale x 8 x i1> @llvm.aarch64.sve.rev.nxv8i1(<vscale x 8 x i1>) #0
declare <vscale x 16 x i1> @llvm.aarch64.sve.rev.nxv16i1(<vscale x 16 x i1>) #0
declare <vscale x 4 x i32> @llvm.aarch64.sve.rev.nxv4i32(<vscale x 4 x i32>) #0
declare <vscale x 2 x i64> @llvm.aarch64.sve.rev.nxv2i64(<vscale x 2 x i64>) #0
declare <vscale x 8 x half> @llvm.aarch64.sve.rev.nxv8f16(<vscale x 8 x half>) #0

attributes #0 = { nocallback nofree nosync nounwind willreturn memory(none) }
